theme: minima
title: Epic website
author: Bruno Munka
email: munka.et3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first epic website.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
